sudo: required
language: generic
services: docker
tex-config:
- tex-scheme=full
- push-type=branch
- build-pattern=main.tex
- packages=lipsum, blindtext, collection-langeuropean, pxfonts, mathpazo, palatino
env:
  global:
  - IS_TRAVIS=true
  - secure: mNuKUCSJ8xutTEfme0eMyWlYB9IJangwe/xa7rPPoO/FjvsO/kjjWITrKC8rAulj7zPaC3WhzLZ4Yv2KtNwivzWRBBoKAYZy7kuRqD4I08Uvuw/Z5l8YTJxRk8L3BaYtpk+XU3GXOv6+RbyMUUG0Yg2rptxljv9kKll714KxYFpgH/7pbwwIEiSyIhp1iDsQWf5Zv3WwyV9CTeASyXP5zst8/icdHH0CFme6N3bBOz3AORuD/kk4LuIAze7dizT47mc0BQEdqfbB7D7f97ngAA3x7VNWEcGM3XEL23MVJlHiXG6l2Ih66zhtU52O00Hi4czZXw7BDEwAaOrfRJi+HXzT6RxqmYYVaw5HpcE4Htr4StIQquMty9KhGap5opH9Qc6e7w4/i8HgF31BVGUD8jImibMlYTKcZscXPzqexlIIvukS0yRJHM037nwyxXvApUoseDE121HbaOq1mOqqa3yGDutCCHZnsTj3/IFhlcbSf0gaCPX6DToaLkz8HIYK7E45iK9nt7tDex093DvRj+p8en4zY76J5lH1lo62m6kre/HtVDv9CKK3FF1SfoO0PX1CepP4ipgOUTt0xJMClFonYKyqMsAV+nrRVnOTo6mno4seQNl3wC9Vs0NRSvGA1qlxd2uxooO+4Qa9+7XWPvzefqVQ1dxRs9WGGcwalDs=
script:
- chmod +x .travis/travis-texbuild.sh
- ".travis/travis-texbuild.sh"
file:
- "./main.pdf"
skip_cleanup: true
true:
  tags: true
  branch: master
